spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkman
    username: checkman
    password: checkman
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 9003

check-man:
  solution:
    location: /tmp/check-man/solution
  template:
    location: /tmp/check-man/template
  playground:
    location: /tmp/check-man/playground
  docker-files:
    location: /tmp/check-man/docker-files

  modules:
    gradle:
      volume:
        container-path: /playground/app/build/test-results

jwt:
  expiration: 2147483647

logging:
  level:
    cz.upce.fei.testingsubsystem.service: DEBUG