logging:
  level:
    tracer: TRACE

jwt:
  secret: MIICXgIBAAKBgQCUMQwvELcqmvcsCfOVEGjqBFX8ckLYuNDq2PrbEw32XnXAnuQE
  expiration: 28800000

check-man:
  solution:
    location: /tmp/check-man/solution
  template:
    location: /tmp/check-man/template
  playground:
    location: /tmp/check-man/playground
  docker-files:
    location: /tmp/check-man/docker-files

  modules:
    container:
      max-memory: 536870912
    gradle:
      volume:
        container-path: /playground/app/build/test-results
      container:
        timeout: 50

my:
  group: ${group}