spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkman
    username: checkman
    password: checkman
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 9003

check-man:
  solution:
    location: /tmp/check-man/solutions
  template:
    location: /tmp/check-man/templates
  playground:
    location: /tmp/check-man/playground
  docker-files:
    location: /tmp/check-man/docker-files

jwt:
  expiration: 2147483647